'use client'

import { useEffect, useMemo, useState, FormEvent } from 'react'
import Link from 'next/link'
import { ArrowRight, Check, Flame, Heart, Leaf, Menu, Search, ShoppingBag, Sparkles, Star, X } from 'lucide-react'

type Product={id:number;name:string;price:number;description:string;category:string;stock:number;rating:number;scent_notes:string;burn_time:string;tag:string}
const fallback:Product[]=[
  {id:1,name:'Lavender Sanctuary',price:38,description:'French lavender, cedarwood, and quiet evening air.',category:'Floral',stock:24,rating:4.9,scent_notes:'Lavender · Cedarwood',burn_time:'50 hours',tag:'Self Care'},
  {id:2,name:'Citrus Sunrise',price:32,description:'Blood orange, lemon, and bergamot for bright mornings.',category:'Citrus',stock:18,rating:4.8,scent_notes:'Bergamot · Lemon',burn_time:'45 hours',tag:'Bestseller'},
  {id:3,name:'Mahogany Nights',price:48,description:'A deep blend of mahogany, leather, and amber.',category:'Woody',stock:9,rating:5,scent_notes:'Mahogany · Amber',burn_time:'60 hours',tag:'Seasonal'},
  {id:4,name:'Fireside Fig',price:42,description:'Ripe fig, smoked oak, and tonka in a warm slow burn.',category:'Spiced',stock:14,rating:4.9,scent_notes:'Fig · Smoked oak',burn_time:'55 hours',tag:'New'}]
const tones=['from-[#c8a98f] to-[#6f5042]','from-[#e5b976] to-[#ad6748]','from-[#766156] to-[#292724]','from-[#a57868] to-[#4b3a35]']

function CandleArt({index=0,large=false}:{index?:number;large?:boolean}){return <div className={`relative overflow-hidden bg-gradient-to-br ${tones[index%tones.length]} ${large?'min-h-[620px]':'aspect-[4/5]'}`}><div className="absolute inset-0 opacity-20 [background-image:radial-gradient(circle_at_30%_20%,white_0,transparent_35%)]"/><div className="absolute left-1/2 top-[28%] h-20 w-px -translate-x-1/2 bg-[#3d2b23]"/><div className="absolute left-1/2 top-[22%] h-12 w-7 -translate-x-1/2 rounded-[50%_50%_45%_45%] bg-[#ffd78a] blur-[1px] shadow-[0_0_40px_15px_rgba(255,200,110,.25)]"/><div className="absolute bottom-[15%] left-1/2 h-[47%] w-[42%] -translate-x-1/2 rounded-[45%_45%_12px_12px] bg-[#f7efe3]/90 shadow-2xl"><div className="absolute inset-x-[14%] top-[38%] border-y border-[#8b8178]/30 py-5 text-center font-serif text-sm tracking-[.22em] text-[#4d453f]">MORROW<br/><span className="text-[9px]">& WICK</span></div></div><span className="absolute bottom-7 left-7 text-xs uppercase tracking-[.25em] text-white/80">Poured by hand</span></div>}

export default function Storefront(){
 const [open,setOpen]=useState(false),[products,setProducts]=useState<Product[]>(fallback),[category,setCategory]=useState('All'),[sort,setSort]=useState('Featured'),[cart,setCart]=useState(0),[wish,setWish]=useState<number[]>([]),[quick,setQuick]=useState<Product|null>(null),[email,setEmail]=useState(''),[sending,setSending]=useState(false),[sent,setSent]=useState(false),[error,setError]=useState('')
 useEffect(()=>{fetch('/api/products').then(r=>r.ok?r.json():Promise.reject()).then(setProducts).catch(()=>{})},[])
 const shown=useMemo(()=>{let p=category==='All'?products:products.filter(x=>x.category===category);return [...p].sort((a,b)=>sort==='Price low'?a.price-b.price:sort==='Rating'?b.rating-a.rating:b.id-a.id)},[products,category,sort])
 async function subscribe(e:FormEvent){e.preventDefault();setSending(true);setError('');try{const r=await fetch(`${process.env.NEXT_PUBLIC_CONSTRUCTOR_API}/v1/forms/${process.env.NEXT_PUBLIC_PROJECT_ID}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,form:'newsletter'})});if(!r.ok)throw Error();setSent(true)}catch{setError('We could not send your note. Please try again.')}finally{setSending(false)}}
 const links=[['Shop','catalog'],['Collections','collections'],['Our story','story'],['For merchants','pricing']]
 return <main>
  <header className="sticky top-0 z-40 border-b border-[#292724]/10 bg-[#fffbf7]/95 backdrop-blur-xl"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 lg:px-8"><Link href="/" className="font-serif text-2xl tracking-wide">Morrow <span className="text-[#c4916f]">&</span> Wick</Link><nav className="hidden gap-8 text-sm md:flex">{links.map(([n,id])=><a key={id} href={`#${id}`} className="hover:text-[#c4916f]">{n}</a>)}</nav><div className="flex items-center gap-4"><button aria-label="Search catalog" onClick={()=>document.getElementById('catalog')?.scrollIntoView()}><Search size={19}/></button><button aria-label="Shopping bag" onClick={()=>document.getElementById('catalog')?.scrollIntoView()} className="relative"><ShoppingBag size={19}/>{cart>0&&<b className="absolute -right-3 -top-3 grid size-5 place-items-center rounded-full bg-[#c4916f] text-[10px] text-white">{cart}</b>}</button><button aria-label="Open menu" onClick={()=>setOpen(!open)} className="md:hidden">{open?<X/>:<Menu/>}</button></div></div><div className={`absolute inset-x-0 top-20 bg-[#fffbf7] px-6 py-7 shadow-xl transition-all duration-500 ease-[cubic-bezier(0.16,1,0.3,1)] md:hidden ${open?'pointer-events-auto translate-y-0 opacity-100':'pointer-events-none -translate-y-4 opacity-0'}`}>{links.map(([n,id],i)=><a key={id} href={`#${id}`} onClick={()=>setOpen(false)} style={{transitionDelay:open?`${i*60}ms`:'0ms'}} className="block border-b py-4 text-lg transition-all">{n}</a>)}</div></header>
  <section className="grid min-h-[calc(100vh-80px)] lg:grid-cols-[42%_58%]"><div className="order-2 flex items-center bg-[#292724] px-6 py-20 text-[#fffbf7] lg:order-1 lg:px-16"><div className="max-w-xl"><p className="mb-7 text-xs uppercase tracking-[.3em] text-[#d6b49d]">Small batch home fragrance</p><h1 className="font-serif text-6xl leading-[.92] sm:text-7xl xl:text-[96px]">Hand poured scents, <em className="font-light text-[#d6b49d]">sustainably</em> crafted.</h1><p className="mt-8 max-w-md text-base leading-7 text-white/65">Discover artisanal candles made with soy wax and essential oils. Every burn tells a story.</p><div className="mt-10 flex items-center gap-7"><a href="#catalog" className="inline-flex items-center gap-3 rounded-full bg-[#fffbf7] px-7 py-4 text-sm font-medium text-[#292724] transition hover:bg-[#c4916f]">Shop now <ArrowRight size={17}/></a><a href="#story" className="border-b border-white/40 pb-1 text-sm">Learn our story</a></div></div></div><div className="order-1 lg:order-2"><CandleArt large/></div></section>
  <section id="collections" className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><div className="mb-12 flex items-end justify-between"><div><p className="eyebrow">Curated for the moment</p><h2>Featured collections</h2></div><a href="#catalog" className="hidden items-center gap-2 text-sm sm:flex">Browse all <ArrowRight size={16}/></a></div><div className="grid gap-5 md:grid-cols-12"><article className="group relative min-h-[490px] overflow-hidden rounded-lg bg-gradient-to-br from-[#7d6253] to-[#302824] p-8 text-white md:col-span-7"><div className="absolute right-10 top-12 h-72 w-52 rounded-[50%_50%_10px_10px] bg-[#f3dfc8]/90 shadow-2xl"/><div className="absolute bottom-8"><span className="text-xs uppercase tracking-[.2em]">Collection 01</span><h3 className="mt-2 font-serif text-4xl">Seasonal bestsellers</h3><p className="mt-2 text-white/65">Warm woods and quiet spice for slower evenings.</p></div></article><div className="grid gap-5 md:col-span-5"><article className="rounded-lg bg-[#e3d5c9] p-7"><Sparkles className="mb-12 text-[#9c6b4f]"/><h3 className="font-serif text-3xl">Self care rituals</h3><p className="mt-2 text-sm text-[#6f6861]">Soft florals made for a deeper exhale.</p></article><article className="rounded-lg bg-[#c4916f] p-7 text-white"><ShoppingBag className="mb-12"/><h3 className="font-serif text-3xl">Gifting sets</h3><p className="mt-2 text-sm text-white/75">Thoughtful pairings, wrapped with intention.</p></article></div></div></section>
  <section id="catalog" className="bg-[#f5f1ed] py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="mb-10 lg:flex lg:items-end lg:justify-between"><div><p className="eyebrow">Find your atmosphere</p><h2>Top rated scents</h2></div><div className="mt-8 flex flex-wrap gap-2 lg:mt-0">{['All','Floral','Citrus','Woody','Spiced'].map(c=><button key={c} onClick={()=>setCategory(c)} className={`rounded-full border px-4 py-2 text-xs ${category===c?'border-[#292724] bg-[#292724] text-white':'border-[#292724]/20'}`}>{c}</button>)}<select value={sort} onChange={e=>setSort(e.target.value)} aria-label="Sort products" className="rounded-full border border-[#292724]/20 bg-transparent px-4 text-xs"><option>Featured</option><option>Price low</option><option>Rating</option></select></div></div><div className="grid gap-x-5 gap-y-12 sm:grid-cols-2 lg:grid-cols-4">{shown.map((p,i)=><article key={p.id} className="group"><div className="relative overflow-hidden rounded-lg"><CandleArt index={i}/><span className="absolute left-4 top-4 rounded-full bg-[#fffbf7] px-3 py-1 text-[10px] uppercase tracking-wider">{p.tag}</span><button onClick={()=>setWish(w=>w.includes(p.id)?w.filter(x=>x!==p.id):[...w,p.id])} aria-label="Save favorite" className="absolute right-4 top-4 grid size-9 place-items-center rounded-full bg-white/90"><Heart size={16} fill={wish.includes(p.id)?'#c4916f':'none'}/></button><div className="absolute inset-x-3 bottom-3 translate-y-20 rounded-md bg-white/95 p-4 opacity-0 transition duration-300 group-hover:translate-y-0 group-hover:opacity-100"><p className="mb-3 text-xs leading-5">{p.description}</p><button onClick={()=>setQuick(p)} className="text-xs font-semibold uppercase tracking-wider">Quick view</button></div></div><div className="mt-5 flex items-start justify-between"><div><p className="mb-1 text-[10px] uppercase tracking-[.2em] text-[#8b8178]">{p.scent_notes}</p><h3 className="font-serif text-2xl">{p.name}</h3><div className="mt-2 flex items-center gap-1 text-xs"><Star size={13} fill="#c4916f" strokeWidth={0}/>{p.rating} · ${p.price}</div></div><button onClick={()=>setCart(c=>c+1)} className="grid size-10 place-items-center rounded-full border border-[#292724]/20 transition hover:bg-[#292724] hover:text-white" aria-label={`Add ${p.name} to cart`}><ShoppingBag size={16}/></button></div></article>)}</div></div></section>
  <section id="story" className="mx-auto max-w-4xl px-5 py-28 text-center"><Flame className="mx-auto mb-7 text-[#c4916f]"/><p className="eyebrow">Made to be lived with</p><h2 className="text-5xl md:text-7xl">Fragrance should feel like <em>home.</em></h2><p className="mx-auto mt-8 max-w-2xl leading-8 text-[#6e6760]">We make each candle in considered batches, using soy wax and essential oils selected for depth, clarity, and a beautiful burn. No loud perfume. Just atmosphere, held in a flame.</p></section>
  <section className="bg-[#c4916f] py-10 text-white"><div className="mx-auto grid max-w-7xl gap-8 px-5 text-center sm:grid-cols-2 lg:grid-cols-4"><Stat n="8,500+" t="Orders delivered"/><Stat n="99.2%" t="Customer satisfaction"/><Stat n="100%" t="Natural ingredients"/><Stat n="2019" t="The beginning"/></div></section>
  <section className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><div className="grid gap-5 lg:grid-cols-3"><div className="rounded-lg bg-[#292724] p-9 text-white lg:row-span-2"><p className="eyebrow text-[#d6b49d]">Browse beautifully</p><h2 className="text-5xl">Your ritual, your way.</h2><div className="mt-16 space-y-5">{['Filter by scent profile','Sort by price, rating, or newest','Save favorites to your wishlist','Free shipping on orders over $50'].map(x=><p key={x} className="flex gap-3 border-b border-white/15 pb-5 text-sm"><Check size={18} className="text-[#d6b49d]"/>{x}</p>)}</div></div><div className="rounded-lg bg-[#e9ddd2] p-9 lg:col-span-2"><Leaf className="mb-20"/><h3 className="font-serif text-4xl">Ingredients you can understand</h3><p className="mt-3 max-w-lg text-sm leading-6 text-[#6e6760]">Soy wax, cotton wicks, essential oils, and fragrance selected for a clean, even burn.</p></div><div className="rounded-lg border p-9"><Flame className="mb-16 text-[#c4916f]"/><h3 className="font-serif text-3xl">Burn guidance</h3><p className="mt-2 text-sm text-[#6e6760]">Simple care notes help every candle glow longer.</p></div><div className="rounded-lg bg-[#f5f1ed] p-9"><Heart className="mb-16 text-[#c4916f]"/><h3 className="font-serif text-3xl">Made with care</h3><p className="mt-2 text-sm text-[#6e6760]">Small batches allow us to mind every detail.</p></div></div></section>
  <section className="bg-[#292724] py-24 text-white"><div className="mx-auto max-w-7xl px-5 lg:px-8"><p className="eyebrow text-[#d6b49d]">Customer stories</p><div className="grid gap-10 lg:grid-cols-3">{[['SM','These candles transform my home into a sanctuary. I have already ordered three times this month.','Sarah M. · Portland, OR'],['JK','I gifted these to my bridesmaids and they all asked where I found them. Exquisite packaging, exquisite scent.','Jennifer K. · Denver, CO'],['AR','Every candle smells exactly like the description. No synthetic nonsense. Pure, genuine, beautiful.','Alex R. · San Francisco, CA']].map(([a,q,n])=><blockquote key={a} className="border-t border-white/20 pt-8"><div className="mb-7 flex text-[#d6b49d]">{[1,2,3,4,5].map(s=><Star key={s} size={14} fill="currentColor"/>)}</div><p className="font-serif text-3xl leading-snug">“{q}”</p><footer className="mt-8 flex items-center gap-3"><span className="grid size-11 place-items-center rounded-full bg-[#c4916f] text-xs">{a}</span><span className="text-xs text-white/60">{n}</span></footer></blockquote>)}</div></div></section>
  <section id="pricing" className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><div className="mb-12 max-w-2xl"><p className="eyebrow">For candle merchants</p><h2>Run your collection with calm.</h2><p className="mt-4 text-[#6e6760]">Fourteen days free on every plan. Manage products, stock, and seasonal edits without developer support.</p></div><div className="grid gap-5 lg:grid-cols-3">{[{n:'Starter',p:99,f:['Up to 50 products','Essential filtering','Email support','Standard checkout']},{n:'Growth',p:249,pop:true,f:['Unlimited products','Advanced analytics','Gift card tools','Cart recovery']},{n:'Premium',p:599,f:['Everything in Growth','API access','Dedicated support','Advanced reporting']}].map(t=><article key={t.n} className={`relative rounded-lg border p-8 ${t.pop?'border-[#c4916f] bg-[#f5f1ed]':''}`}>{t.pop&&<span className="absolute right-6 top-6 rounded-full bg-[#c4916f] px-3 py-1 text-[10px] uppercase tracking-wider text-white">Most popular</span>}<h3 className="font-serif text-3xl">{t.n}</h3><p className="my-8"><span className="font-serif text-5xl">${t.p}</span><span className="text-xs text-[#8b8178]"> / month</span></p><ul className="space-y-4 text-sm">{t.f.map(f=><li key={f} className="flex gap-2"><Check size={16} className="text-[#c4916f]"/>{f}</li>)}</ul><a href="#newsletter" className="mt-10 flex justify-center rounded-full bg-[#292724] px-5 py-3 text-sm text-white">Start free trial</a></article>)}</div></section>
  <section id="newsletter" className="bg-[#e9ddd2] py-20"><div className="mx-auto flex max-w-6xl flex-col items-center justify-between gap-8 px-5 text-center lg:flex-row lg:text-left"><div><p className="eyebrow">Notes from the studio</p><h2 className="text-5xl">A slower kind of inbox.</h2><p className="mt-3 text-sm text-[#6e6760]">New scents, care rituals, and seasonal stories.</p></div>{sent?<p className="rounded-full bg-white px-6 py-4">✓ Mensaje enviado — te contactaremos pronto</p>:<form onSubmit={subscribe} className="w-full max-w-md"><div className="flex rounded-full bg-white p-2"><input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Your email address" aria-label="Email address" className="min-w-0 flex-1 bg-transparent px-4 outline-none"/><button disabled={sending} className="rounded-full bg-[#292724] px-6 py-3 text-sm text-white">{sending?'Enviando…':'Subscribe'}</button></div>{error&&<p className="mt-2 text-sm text-red-800">{error}</p>}</form>}</div></section>
  <section className="px-5 py-24 text-center"><h2 className="mx-auto max-w-3xl text-6xl md:text-8xl">Light a little <em>stillness.</em></h2><a href="#catalog" className="mt-10 inline-flex items-center gap-3 rounded-full bg-[#c4916f] px-8 py-4 text-sm text-white">Find your scent <ArrowRight size={17}/></a></section>
  <footer className="bg-[#292724] px-5 py-16 text-white"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-4"><div className="lg:col-span-2"><p className="font-serif text-3xl">Morrow <span className="text-[#c4916f]">&</span> Wick</p><p className="mt-4 max-w-xs text-sm leading-6 text-white/50">Hand poured home fragrance for mindful, beautifully lived days.</p></div><div><p className="mb-4 text-xs uppercase tracking-widest text-white/40">Explore</p>{links.slice(0,3).map(([n,id])=><a key={id} href={`#${id}`} className="mb-3 block text-sm">{n}</a>)}</div><div><p className="mb-4 text-xs uppercase tracking-widest text-white/40">Merchant tools</p><a href="#pricing" className="mb-3 block text-sm">Plans</a><Link href="/login" className="block text-sm">Admin login</Link></div></div><div className="mx-auto mt-16 flex max-w-7xl flex-col justify-between gap-3 border-t border-white/10 pt-6 text-xs text-white/35 sm:flex-row"><span>© 2026 Morrow & Wick</span><span>Made with care, designed to last</span></div></footer>
  {quick&&<div role="dialog" aria-modal="true" className="fixed inset-0 z-50 grid place-items-center bg-black/60 p-5" onClick={()=>setQuick(null)}><div className="grid w-full max-w-3xl overflow-hidden rounded-xl bg-[#fffbf7] sm:grid-cols-2" onClick={e=>e.stopPropagation()}><CandleArt/><div className="relative p-8"><button onClick={()=>setQuick(null)} aria-label="Close quick view" className="absolute right-5 top-5"><X/></button><p className="eyebrow">{quick.category}</p><h2 className="text-4xl">{quick.name}</h2><p className="mt-5 leading-7 text-[#6e6760]">{quick.description}</p><dl className="mt-8 space-y-3 text-sm"><div className="flex justify-between border-b pb-3"><dt>Scent notes</dt><dd>{quick.scent_notes}</dd></div><div className="flex justify-between border-b pb-3"><dt>Burn time</dt><dd>{quick.burn_time}</dd></div><div className="flex justify-between"><dt>Availability</dt><dd>{quick.stock>0?'In stock':'Out of stock'}</dd></div></dl><button onClick={()=>{setCart(c=>c+1);setQuick(null)}} className="mt-8 w-full rounded-full bg-[#292724] py-4 text-white">Add to bag · ${quick.price}</button></div></div></div>}
 </main>
}
function Stat({n,t}:{n:string;t:string}){return <div><b className="font-serif text-4xl">{n}</b><p className="mt-1 text-xs uppercase tracking-wider text-white/70">{t}</p></div>}
